---
# OOB Management network default gateway
# mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
# mgmt_interface: Management0
mgmt_interface_vrf: default

name_servers:
#  - 192.168.2.1
  - 8.8.8.8

# dns_domain: atd.lab

local_users:

  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "{{ user_pass | password_hash('sha512', salt='arista') }}"
   
cvp_instance_ips:
  - apiserver.arista.io
terminattr_disable_aaa: True
#terminattr_ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
#terminattr_ingestgrpcurl_port: 9910
#terminattr_smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

ntp:
  servers:
    - name: 0.north-america.pool.ntp.org
      iburst: True
#      local_interface: Management0

aaa_authentication:
  login:
    default: local
aaa_authorization:
  exec:
    default: local
  commands:
    all_default: local
#aaa_server_groups:
#  - name: atds
#    type: radius
#    servers:
#      - server: 192.168.0.1
