---
- name: Trigger GitHub Action via Python Script
  hosts: localhost
  gather_facts: false

  vars:
    inputs:
      environment: "master"
      #debug_mode: "false"

  tasks:
    - name: Trigger GitHub workflow_dispatch
      ansible.builtin.command: >
        python3 scripts/validate_workflow.py '{{ inputs | to_json }}'
      environment:
        GITHUB_REPO: ramzihusein/atd-avd
        WORKFLOW_FILE: validate.yml
        GITHUB_TOKEN: "{{ token }}"
        GITHUB_REF: master
    - name: Wait for validation to complete successfully
      ansible.builtin.uri:
        url: https://api.github.com/repos/ramzihusein/atd-avd/actions/runs/
        method: GET
        return_content: true
        body_format: json
      register: runs
    - name: Wait for validation to complete successfully
      ansible.builtin.uri:
        url: https://api.github.com/repos/ramzihusein/atd-avd/actions/runs/{{ runs.workflow_runs[0].id }}
        method: GET
        return_content: true
        body_format: json
      register: results
      retries: 100
      delay: 10
      until: results.status == "success"
