---

name: "Network Validation"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The branch to validate"
        required: true
        default: "demo"

jobs:
  validate:
    runs-on: self-hosted
    env:
      ANSIBLE_USERNAME: ${{ secrets.ANSIBLE_USERNAME }}
      ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Validation Playbook
        run: |
          ansible-playbook playbooks/validate.yml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation-report
          path: atd-inventory/reports/**
          retention-days: 1
