---

name: "Network Validation"

on:
  push:
    branches:
      - master
    paths:
      - 'atd-inventory/group_vars/**'
      - 'atd-inventory/host_vars/**'

jobs:
  validate:
    runs-on: self-hosted
    env:
      ANSIBLE_USERNAME: ${{ secrets.ANSIBLE_USERNAME }}
      ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Validation Playbook
        run: |
          ansible-playbook playbooks/validate.yml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation-report
          path: atd-inventory/reports/**
          retention-days: 1
